import type { QuestionnaireSchema } from "@/lib/survey-engine/types";

const o = (value: string, label: string) => ({ value, label });

export const aiDemandSchema: QuestionnaireSchema = {
  id: "ai-demand",
  version: 1,
  title: "高端AI智慧养老服务需求调查问卷",
  intro:
    "您好！本问卷旨在了解长者及家属对智能养老、AI养老设备和高端养老服务的真实需求与看法。问卷默认匿名，答案没有对错，请根据实际情况勾选或填写。开放题已留出较大书写空间。感谢您的支持！",
  sections: [
    {
      id: "basic",
      title: "一、基本信息",
      questions: [
        {
          id: "q1",
          type: "single",
          title: "您的身份是？",
          required: true,
          allowOther: true,
          options: [
            o("elder", "长者本人"),
            o("family", "长者家属"),
            o("staff", "养老院工作人员"),
            o("other", "其他"),
          ],
        },
        {
          id: "q2",
          type: "single",
          title: "您的年龄段是？",
          required: true,
          options: [
            o("under60", "60岁以下"),
            o("60s", "60–69岁"),
            o("70s", "70–79岁"),
            o("80plus", "80岁及以上"),
          ],
        },
        {
          id: "q3",
          type: "single",
          title: "您目前的居住/照护方式是？",
          required: true,
          allowOther: true,
          options: [
            o("home", "居家养老"),
            o("facility", "养老院/护理院"),
            o("children", "与子女同住"),
            o("daycare", "社区日间照料"),
            o("other", "其他"),
          ],
        },
        {
          id: "q4",
          type: "single",
          title: "您目前是否需要日常生活协助？",
          required: true,
          options: [
            o("rarely", "基本不需要"),
            o("sometimes", "偶尔需要"),
            o("often", "经常需要"),
            o("mostly", "大部分时间都需要"),
          ],
        },
      ],
    },
    {
      id: "awareness",
      title: "二、智能养老的了解与使用",
      questions: [
        {
          id: "q5",
          type: "single",
          title: "您是否接触或使用过智能养老设备（如智能手环、跌倒监测、健康监测床、AI呼叫设备等）？",
          required: true,
          options: [
            o("often", "经常使用"),
            o("sometimes", "偶尔使用"),
            o("heard", "听说过但没使用过"),
            o("never", "从未接触"),
          ],
        },
        {
          id: "q6",
          type: "single",
          title: "您认为AI智能设备是否能提升养老生活的安全感和便利度？",
          required: true,
          options: [
            o("very", "非常有帮助"),
            o("some", "有一定帮助"),
            o("unsure", "不确定/没感觉"),
            o("distrust", "不太信任"),
            o("none", "完全不需要"),
          ],
        },
        {
          id: "q7",
          type: "multi",
          title: "您最希望智能养老设备解决哪些问题？",
          required: true,
          allowOther: true,
          options: [
            o("fall", "跌倒、离床、突发情况预警"),
            o("vitals", "心率、血压、睡眠等健康监测"),
            o("meds", "用药提醒"),
            o("sos", "紧急呼叫家属或护理人员"),
            o("companion", "陪伴聊天、娱乐互动"),
            o("delivery", "送餐、送药、取物等服务"),
            o("doctor", "帮助联系医生或线上问诊"),
            o("other", "其他"),
          ],
        },
      ],
    },
    {
      id: "demand",
      title: "三、高端AI智慧养老服务的需求",
      questions: [
        {
          id: "q8",
          type: "multi",
          title: "如果养老院提供以下AI智慧养老服务，您最感兴趣的是哪些？",
          required: true,
          allowOther: true,
          options: [
            o("monitor24", "24小时AI安全监测"),
            o("healthdata", "AI健康数据记录与分析"),
            o("voice", "智能语音陪伴与情绪关怀"),
            o("remind", "智能用药提醒与护理提醒"),
            o("robot", "送物/送餐机器人"),
            o("rehab", "康复训练辅助设备"),
            o("remote", "家属远程查看健康和生活状态"),
            o("personal", "个性化饮食、运动、护理建议"),
            o("room", "智能房间：灯光、温度、呼叫自动调节"),
            o("other", "其他"),
          ],
        },
        {
          id: "q9",
          type: "multi",
          title: "您认为“高端养老服务”最重要的特点是什么？",
          required: true,
          options: [
            o("medical", "医疗护理专业"),
            o("env", "环境舒适安静"),
            o("staff", "服务人员耐心负责"),
            o("food", "饮食营养健康"),
            o("safety", "安全保障完善"),
            o("activity", "娱乐活动丰富"),
            o("family", "家属沟通方便"),
            o("dignity", "尊重长者隐私和尊严"),
            o("tech", "科技设备先进但易用"),
            o("price", "价格合理透明"),
          ],
        },
        {
          id: "q10",
          type: "multi",
          title: "您对AI设备进入养老院最大的担心是什么？",
          required: true,
          allowOther: true,
          options: [
            o("hard", "不会使用，操作太复杂"),
            o("privacy", "担心隐私被泄露"),
            o("error", "担心设备出错或不准确"),
            o("lonely", "担心减少人与人之间的陪伴"),
            o("cost", "价格太高"),
            o("maintain", "维修和维护麻烦"),
            o("none", "没有明显担心"),
            o("other", "其他"),
          ],
        },
        {
          id: "q11",
          type: "single",
          title: "您是否愿意尝试由AI或机器人辅助完成部分养老服务？",
          required: true,
          options: [
            o("very", "非常愿意"),
            o("try", "可以尝试"),
            o("depends", "不确定，要看具体服务"),
            o("reluctant", "不太愿意"),
            o("no", "完全不愿意"),
          ],
        },
        {
          id: "q12",
          type: "single",
          title: "如果AI智慧养老服务需要额外收费，您认为每月可接受的费用大约是？",
          required: true,
          options: [
            o("none", "不愿额外付费"),
            o("lt500", "500元以下"),
            o("500_1000", "500–1000元"),
            o("1000_3000", "1000–3000元"),
            o("gt3000", "3000元以上"),
            o("depends", "视服务内容而定"),
          ],
        },
      ],
    },
    {
      id: "improve",
      title: "四、改进建议",
      questions: [
        {
          id: "q13",
          type: "multi",
          title: "您认为目前养老院/养老服务中最需要改善的地方是什么？",
          required: true,
          allowOther: true,
          options: [
            o("staffing", "护理人员数量不足"),
            o("medical", "医疗资源不足"),
            o("emergency", "紧急情况反应速度"),
            o("company", "活动与陪伴较少"),
            o("meals", "饮食选择有限"),
            o("room", "房间设施不够便利"),
            o("family", "与家属沟通不够及时"),
            o("fee", "费用较高"),
            o("other", "其他"),
          ],
        },
        {
          id: "q14",
          type: "longtext",
          title: "您希望养老院未来增加哪些服务或设备？",
        },
        {
          id: "q15",
          type: "longtext",
          title: "您觉得长者在使用智能设备时，最需要哪方面的帮助？",
        },
        {
          id: "q16",
          type: "single",
          title: "您是否愿意接受学生后续进行简短访谈，了解您的使用体验？",
          required: true,
          options: [
            o("yes", "愿意"),
            o("no", "不愿意"),
            o("maybe", "可以，但需要提前说明并征得同意"),
          ],
        },
        {
          id: "q16_contact",
          type: "longtext",
          title: "如愿意，可留下称呼/联系方式（自愿填写）",
          showIf: { questionId: "q16", equals: ["yes", "maybe"] },
        },
      ],
    },
    {
      id: "overall",
      title: "五、总体评价",
      questions: [
        {
          id: "q17",
          type: "single",
          title: "您对“AI智慧养老”的整体态度是？",
          required: true,
          options: [
            o("eager", "非常期待"),
            o("support", "比较支持"),
            o("watch", "保持观望"),
            o("low", "不太支持"),
            o("no", "完全不支持"),
          ],
        },
        {
          id: "q18",
          type: "longtext",
          title: "请用一句话描述您理想中的养老生活",
        },
      ],
    },
  ],
};
