import type { QuestionnaireSchema } from "@/lib/survey-engine/types";

const o = (value: string, label: string) => ({ value, label });

export const aiDemandSchema: QuestionnaireSchema = {
  id: "ai-demand",
  version: 1,
  title: "Needs survey for high-end AI elderly care",
  intro:
    "Hello. This survey asks how elders and families feel about intelligent care, AI care devices, and high-end care services. It is anonymous by default. There are no right or wrong answers. Please tick or write what is true for you. Open questions have room to write. Thank you for your support.",
  sections: [
    {
      id: "basic",
      title: "1. About you",
      questions: [
        {
          id: "q1",
          type: "single",
          title: "Who are you?",
          required: true,
          allowOther: true,
          options: [
            o("elder", "The elder"),
            o("family", "A family member"),
            o("staff", "A staff member"),
            o("other", "Someone else"),
          ],
        },
        {
          id: "q2",
          type: "single",
          title: "Which age group are you in?",
          required: true,
          options: [
            o("under60", "Under 60"),
            o("60s", "60–69"),
            o("70s", "70–79"),
            o("80plus", "80 or older"),
          ],
        },
        {
          id: "q3",
          type: "single",
          title: "How do you live and receive care now?",
          required: true,
          allowOther: true,
          options: [
            o("home", "Living at home"),
            o("facility", "A care home or nursing home"),
            o("children", "Living with children"),
            o("daycare", "Community day care"),
            o("other", "Other"),
          ],
        },
        {
          id: "q4",
          type: "single",
          title: "Do you need help with daily living?",
          required: true,
          options: [
            o("rarely", "Almost never"),
            o("sometimes", "Sometimes"),
            o("often", "Often"),
            o("mostly", "Most of the time"),
          ],
        },
      ],
    },
    {
      id: "awareness",
      title: "2. Knowing and using intelligent care",
      questions: [
        {
          id: "q5",
          type: "single",
          title: "Have you used intelligent care devices, such as a band, fall alert, health bed, or AI call button?",
          required: true,
          options: [
            o("often", "I use them often"),
            o("sometimes", "I use them sometimes"),
            o("heard", "I have heard of them but not used them"),
            o("never", "I have never used them"),
          ],
        },
        {
          id: "q6",
          type: "single",
          title: "Can AI devices make care feel safer and easier?",
          required: true,
          options: [
            o("very", "Very helpful"),
            o("some", "Somewhat helpful"),
            o("unsure", "Not sure / no strong feeling"),
            o("distrust", "I do not quite trust them"),
            o("none", "I do not need them at all"),
          ],
        },
        {
          id: "q7",
          type: "multi",
          title: "Which problems should intelligent devices help with most?",
          required: true,
          allowOther: true,
          options: [
            o("fall", "Alerts for falls, leaving bed, or sudden trouble"),
            o("vitals", "Health checks such as heart rate, blood pressure, and sleep"),
            o("meds", "Medicine reminders"),
            o("sos", "Calling family or nurses in an emergency"),
            o("companion", "Company, talk, and simple play"),
            o("delivery", "Help bringing meals, medicine, or things"),
            o("doctor", "Help reaching a doctor or a video visit"),
            o("other", "Other"),
          ],
        },
      ],
    },
    {
      id: "demand",
      title: "3. What high-end AI care should offer",
      questions: [
        {
          id: "q8",
          type: "multi",
          title: "If the home offered these AI care services, which would interest you most?",
          required: true,
          allowOther: true,
          options: [
            o("monitor24", "24-hour AI safety watch"),
            o("healthdata", "AI health records and review"),
            o("voice", "Voice company and gentle emotional care"),
            o("remind", "Medicine and care reminders"),
            o("robot", "A robot that brings meals or things"),
            o("rehab", "Help with rehabilitation exercises"),
            o("remote", "Family can see health and daily life from afar"),
            o("personal", "Personal advice on meals, movement, and care"),
            o("room", "A smart room for lights, warmth, and calling"),
            o("other", "Other"),
          ],
        },
        {
          id: "q9",
          type: "multi",
          title: "What matters most in high-end elderly care?",
          required: true,
          options: [
            o("medical", "Skilled medical and nursing care"),
            o("env", "A quiet, comfortable place"),
            o("staff", "Patient, responsible staff"),
            o("food", "Healthy, nourishing meals"),
            o("safety", "Strong safety"),
            o("activity", "Plenty of activities"),
            o("family", "Easy contact with family"),
            o("dignity", "Privacy and dignity"),
            o("tech", "Advanced tools that are still easy to use"),
            o("price", "Clear, fair prices"),
          ],
        },
        {
          id: "q10",
          type: "multi",
          title: "What worries you most about AI devices in a care home?",
          required: true,
          allowOther: true,
          options: [
            o("hard", "Too hard to use"),
            o("privacy", "Worry about privacy"),
            o("error", "Worry the device is wrong or fails"),
            o("lonely", "Worry it replaces human company"),
            o("cost", "Too expensive"),
            o("maintain", "Hard to repair and look after"),
            o("none", "No strong worry"),
            o("other", "Other"),
          ],
        },
        {
          id: "q11",
          type: "single",
          title: "Would you try letting AI or a robot help with some care?",
          required: true,
          options: [
            o("very", "Very willing"),
            o("try", "Willing to try"),
            o("depends", "Not sure — it depends on the service"),
            o("reluctant", "Not very willing"),
            o("no", "Not willing at all"),
          ],
        },
        {
          id: "q12",
          type: "single",
          title: "If AI care cost extra, what monthly fee would feel acceptable?",
          required: true,
          options: [
            o("none", "I would not pay extra"),
            o("lt500", "Under 500 yuan"),
            o("500_1000", "500–1,000 yuan"),
            o("1000_3000", "1,000–3,000 yuan"),
            o("gt3000", "More than 3,000 yuan"),
            o("depends", "It depends on what is offered"),
          ],
        },
      ],
    },
    {
      id: "improve",
      title: "4. What could be better",
      questions: [
        {
          id: "q13",
          type: "multi",
          title: "What in care homes or care services most needs to improve?",
          required: true,
          allowOther: true,
          options: [
            o("staffing", "Not enough care staff"),
            o("medical", "Not enough medical support"),
            o("emergency", "Slow response in an emergency"),
            o("company", "Too little activity and company"),
            o("meals", "Limited meal choices"),
            o("room", "Rooms that are not easy to use"),
            o("family", "Slow contact with family"),
            o("fee", "Fees that feel high"),
            o("other", "Other"),
          ],
        },
        {
          id: "q14",
          type: "longtext",
          title: "What services or devices would you like the home to add?",
        },
        {
          id: "q15",
          type: "longtext",
          title: "When elders use intelligent devices, what help do they need most?",
        },
        {
          id: "q16",
          type: "single",
          title: "May a student later have a short talk with you about how this felt?",
          required: true,
          options: [
            o("yes", "Yes"),
            o("no", "No"),
            o("maybe", "Yes, if you explain first and ask my consent"),
          ],
        },
        {
          id: "q16_contact",
          type: "longtext",
          title: "If yes, you may leave a name or a way to reach you. This is optional.",
          showIf: { questionId: "q16", equals: ["yes", "maybe"] },
        },
      ],
    },
    {
      id: "overall",
      title: "5. Overall view",
      questions: [
        {
          id: "q17",
          type: "single",
          title: "Overall, how do you feel about AI intelligent care?",
          required: true,
          options: [
            o("eager", "I look forward to it"),
            o("support", "I mostly support it"),
            o("watch", "I am watching and waiting"),
            o("low", "I do not quite support it"),
            o("no", "I do not support it at all"),
          ],
        },
        {
          id: "q18",
          type: "longtext",
          title: "In one sentence, what would an ideal later life feel like?",
        },
      ],
    },
  ],
};
